from machine import Pin 
import time

l1 = Pin(32, Pin.OUT)
l2 = Pin(33, Pin.OUT)
l3 = Pin(25, Pin.OUT)
l4 = Pin(26, Pin.OUT)
l5 = Pin(27, Pin.OUT)
l6 = Pin(14, Pin.OUT)
l7 = Pin(12, Pin.OUT)
l8 = Pin(13, Pin.OUT)  


while True:
    l1.on()
    time.sleep(0.5)
    l1.off()    
    l2.on()
    time.sleep(0.5)
    l2.off()    
    l3.on()
    time.sleep(0.5)
    l3.off()    
    l4.on()
    time.sleep(0.5)
    l4.off()    
    l5.on()
    time.sleep(0.5)
    l5.off()    
    l6.on()
    time.sleep(0.5)
    l6.off()    
    l7.on()
    time.sleep(0.5)
    l7.off()    
    l8.on()
    time.sleep(0.5)
    l8.off()        
    l7.on()
    time.sleep(0.5)
    l7.off()        
    l6.on()
    time.sleep(0.5)
    l6.off()        
    l5.on()
    time.sleep(0.5)
    l5.off()        
    l4.on()
    time.sleep(0.5)
    l4.off()        
    l3.on()
    time.sleep(0.5)
    l3.off()        
    l2.on()
    time.sleep(0.5)
    l2.off()
    l1.on()
    time.sleep(0.5)
    l1.off()
